name = "morethan-log"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "yarn build"
[build.environment]
NODE_VERSION = "18"

[site]
bucket = ".next/static"
entry-point = "."
